/**
 * gen-sandbox-entries — from src/sandbox/registry.ts, emit a thin standalone
 * Vite dev entry per harness: <name>-sandbox.html + src/<name>-sandbox-main.tsx.
 * These are dev-only (never added to rollupOptions.input). --check fails if stale.
 * Run: npx tsx scripts/gen-sandbox-entries.ts [--check]
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, unlinkSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SANDBOXES } from '../src/sandbox/registry'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const BANNER = '<!-- GENERATED by scripts/gen-sandbox-entries.ts — do not edit by hand. -->'
const TS_BANNER = '// GENERATED by scripts/gen-sandbox-entries.ts — do not edit by hand.'

function htmlFor(name: string): string {
  return `${BANNER}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <title>Sombra · ${name} sandbox</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/${name}-sandbox-main.tsx"></script>
  </body>
</html>
`
}

function mainFor(name: string): string {
  return `${TS_BANNER}
import { createRoot } from 'react-dom/client'
import './index.css'
import Harness from './sandbox/harnesses/${name}'

// No StrictMode: dev double-invoke mounts → disposes → remounts the WebGPU
// renderer, and disposing destroys the shared GPUDevice, leaving a dead
// canvas for any harness that owns a renderer. The app's real src/main.tsx
// keeps StrictMode.
createRoot(document.getElementById('root')!).render(<Harness />)
`
}

interface Gen { path: string; text: string }
function planned(): Gen[] {
  const out: Gen[] = []
  for (const s of SANDBOXES) {
    out.push({ path: join(ROOT, `${s.name}-sandbox.html`), text: htmlFor(s.name) })
    out.push({ path: join(ROOT, `src/${s.name}-sandbox-main.tsx`), text: mainFor(s.name) })
  }
  return out
}

// Any generated file (recognised by banner) not in the plan is stale → prune target.
function stalePaths(planPaths: Set<string>): string[] {
  const found: string[] = []
  for (const f of readdirSync(ROOT)) {
    if (f.endsWith('-sandbox.html')) {
      const p = join(ROOT, f)
      if (readFileSync(p, 'utf8').startsWith(BANNER) && !planPaths.has(p)) found.push(p)
    }
  }
  for (const f of readdirSync(join(ROOT, 'src'))) {
    if (f.endsWith('-sandbox-main.tsx')) {
      const p = join(ROOT, 'src', f)
      if (readFileSync(p, 'utf8').startsWith(TS_BANNER) && !planPaths.has(p)) found.push(p)
    }
  }
  return found
}

const check = process.argv.includes('--check')
const plan = planned()
const planPaths = new Set(plan.map((g) => g.path))
const stale = stalePaths(planPaths)

if (check) {
  let ok = true
  for (const g of plan) {
    if (!existsSync(g.path) || readFileSync(g.path, 'utf8') !== g.text) {
      console.error(`✗ out of date: ${g.path.replace(ROOT + '/', '')}`)
      ok = false
    }
  }
  for (const p of stale) { console.error(`✗ stale generated entry: ${p.replace(ROOT + '/', '')}`); ok = false }
  if (!ok) { console.error('run `npm run sandbox:gen`'); process.exit(1) }
  console.log('✓ sandbox entries up to date')
} else {
  for (const g of plan) writeFileSync(g.path, g.text)
  for (const p of stale) unlinkSync(p)
  console.log(`✓ wrote ${plan.length} files for ${SANDBOXES.length} harness(es); pruned ${stale.length} stale`)
}
