import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { normalizeIcon, svgToNode } from './lib/normalize-icon'
import type { IconNode } from '../src/icons/create-icon'

const require = createRequire(import.meta.url)
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SVG_DIR = join(ROOT, 'src/icons/svg')
const MANIFEST = join(ROOT, 'src/icons/icon-manifest.json')
const NODES_OUT = join(ROOT, 'src/generated/icon-nodes.ts')

const lucideDir = join(dirname(require.resolve('lucide-static/package.json')), 'icons')
const manifest: Record<string, string> = JSON.parse(readFileSync(MANIFEST, 'utf8'))

function lucidePath(lucideName: string): string {
  return join(lucideDir, `${lucideName}.svg`)
}

// Read every owned SVG on disk, re-derive its IconNode, and emit icon-nodes.ts.
// Returns the generated file text (for --check without writing).
async function buildNodesFile(): Promise<string> {
  const names = Object.keys(manifest).sort((a, b) => a.localeCompare(b))
  const entries: string[] = []
  for (const name of names) {
    const svg = readFileSync(join(SVG_DIR, `${name}.svg`), 'utf8')
    // owned SVG is already 16-grid — use svgToNode (no scaling), never normalizeIcon here.
    const node: IconNode = await svgToNode(svg)
    entries.push(`export const ${name}: IconNode = ${JSON.stringify(node)}`)
  }
  return (
    `// GENERATED by scripts/generate-icons.ts — do not edit by hand.\n` +
    `import type { IconNode } from '@/icons/create-icon'\n\n` +
    entries.join('\n') +
    '\n'
  )
}

async function gen({ check }: { check: boolean }) {
  const text = await buildNodesFile()
  if (check) {
    const current = readFileSync(NODES_OUT, 'utf8')
    if (current !== text) {
      console.error('✗ src/generated/icon-nodes.ts is out of date — run `npm run icons:gen`')
      process.exit(1)
    }
    console.log('✓ icon-nodes.ts up to date')
    return
  }
  writeFileSync(NODES_OUT, text)
  console.log(`✓ wrote ${NODES_OUT} (${Object.keys(manifest).length} icons)`)
}

// Download one lucide icon into the owned set, then regenerate nodes.
async function add(code: string, lucide: string) {
  if (!lucide) throw new Error('usage: icons:add <codeName> <lucideName>')
  const { svgText } = await normalizeIcon(readFileSync(lucidePath(lucide), 'utf8'))
  mkdirSync(SVG_DIR, { recursive: true })
  writeFileSync(join(SVG_DIR, `${code}.svg`), svgText + '\n')
  manifest[code] = lucide
  writeFileSync(MANIFEST, JSON.stringify(sortKeys(manifest), null, 2) + '\n')
  await gen({ check: false })
  console.log(`✓ added ${code} (lucide: ${lucide})`)
}

// First-time population: write every owned SVG from lucide per the manifest, then gen.
async function seed() {
  mkdirSync(SVG_DIR, { recursive: true })
  for (const [code, lucide] of Object.entries(manifest)) {
    const { svgText } = await normalizeIcon(readFileSync(lucidePath(lucide), 'utf8'))
    writeFileSync(join(SVG_DIR, `${code}.svg`), svgText + '\n')
    console.log(`  ${code} ← ${lucide}`)
  }
  await gen({ check: false })
}

function sortKeys(o: Record<string, string>) {
  return Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)))
}

const [cmd, a1, a2] = process.argv.slice(2)
const run = {
  gen: () => gen({ check: process.argv.includes('--check') }),
  seed: () => seed(),
  add: () => add(a1, a2),
}[cmd ?? 'gen']
if (!run) { console.error(`unknown command: ${cmd}`); process.exit(1) }
await run()
