// GENERATED by scripts/gen-sandbox-entries.ts — do not edit by hand.
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import Harness from './sandbox/harnesses/editor-chrome'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <Harness />
  </StrictMode>,
)
