// GENERATED by scripts/gen-sandbox-entries.ts — do not edit by hand.
import { createRoot } from 'react-dom/client'
import './index.css'
import Harness from './sandbox/harnesses/srt-renderer'

// No StrictMode: dev double-invoke mounts → disposes → remounts the WebGPU
// renderer, and disposing destroys the shared GPUDevice, leaving a dead
// canvas for any harness that owns a renderer. The app's real src/main.tsx
// keeps StrictMode.
createRoot(document.getElementById('root')!).render(<Harness />)
